image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r index.html css js Data Prompt Script .public || true
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"
